# Generated by Django 5.2 on 2025-07-10 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowMeterReadingFile',
            fields=[
                ('file_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('header', models.CharField(max_length=100)),
                ('footer', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'D0010 Flow Meter Readings File',
                'verbose_name_plural': 'D00010 Flow Meter Readings Files',
            },
        ),
        migrations.CreateModel(
            name='FlowMeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpan_core', models.IntegerField()),
                ('bsc_validation_status', models.CharField(max_length=1)),
                ('meter_id', models.CharField(max_length=10)),
                ('reading_type', models.CharField(default='', max_length=1)),
                ('meter_register_id', models.CharField(max_length=2)),
                ('reading_date_time', models.DateTimeField()),
                ('register_reading', models.DecimalField(decimal_places=1, max_digits=10)),
                ('reset_date_time', models.DateTimeField(blank=True, null=True)),
                ('number_of_md_resets', models.IntegerField(blank=True, null=True)),
                ('meter_reading_flag', models.BooleanField()),
                ('reading_method', models.CharField(max_length=1)),
                ('file_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow_files.flowmeterreadingfile')),
            ],
            options={
                'verbose_name': 'Flow Meter Reading',
                'verbose_name_plural': 'Flow Meter Readings',
                'unique_together': {('mpan_core', 'meter_id', 'reading_date_time')},
            },
        ),
    ]
