# Generated by Django 5.2 on 2025-07-10 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flowmeterreading',
            unique_together=set(),
        ),
    ]
