# Generated by Django 5.2 on 2025-07-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow_files', '0002_alter_flowmeterreading_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlowMeterReadingFile',
            new_name='D0010File',
        ),
    ]
